kind: Service
apiVersion: v1
metadata:
  name: nodeport-service
  namespace: wso2
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - nodePort: 30165
      protocol: TCP
      port: 80
      targetPort: 8080