apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: wso2
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080