apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: wso2
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 60001
      targetPort: 8080